import { cookies } from "next/headers";
import { auth } from "@/auth";
import { ETheme } from "@/models/enums/theme";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/jetbrains-mono/400.css";
import "@fontsource/jetbrains-mono/500.css";
import { getCookie } from "cookies-next";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { PageTransitionProvider } from "@/components/providers/PageTransitionProvider";
import { SessionProvider } from "@/components/providers/SessionProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "sunxu42",
    template: "%s | sunxu42",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieTheme = await getCookie("app:theme", { cookies });
  const theme = cookieTheme || ETheme.LIGHT;
  const session = await auth();

  return (
    <html suppressHydrationWarning className={theme === "dark" ? "dark" : ""}>
      <body className="w-full antialiased flex justify-center items-center min-h-screen">
        <ThemeProvider attribute="class" storageKey="app:theme" defaultTheme={theme} enableSystem>
          <SessionProvider session={session}>
            <PageTransitionProvider>{children}</PageTransitionProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
