import { Inter, JetBrains_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { auth } from "@/auth";
import { ETheme } from "@/models/enums/theme";
import { getCookie } from "cookies-next";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ThemeProvider } from "next-themes";
import { SessionProvider } from "@/components/providers/session-provider";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "sunxu42",
    template: "%s | sunxu42",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  const cookieTheme = await getCookie("app:theme", { cookies });
  const theme = cookieTheme || ETheme.LIGHT;

  const messages = await getMessages();
  const session = await auth();

  return (
    <html lang={locale} suppressHydrationWarning className={theme === "dark" ? "dark" : ""}>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased flex justify-center items-center min-h-screen`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute="class" storageKey="app:theme" defaultTheme={theme} enableSystem>
            <SessionProvider session={session}>{children}</SessionProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
